# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_White_and_Fluffy_06_2022' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_White_and_Fluffy_06_2022
pod 'SDWebImage', '~> 5.0'
end
